services:
  backend:
    build: ./
    container_name: playvault_container
    working_dir: /playvault
    ports:
      - "8008:8008"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/playvault/src
      - ./commands:/playvault/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5000:80'
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:8-noble
    container_name: mongo_db_container
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    restart: on-failure

  mongoadmin:
    image: mongo-express
    restart: on-failure
    container_name: mongo_admin_container
    ports:
      - '8081:8081'
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  pg_data: { }
  pg_admin: { }
  mongo_data: { }