# Generated by Django 4.2.16 on 2024-10-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_release_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_year",
            field=models.IntegerField(),
        ),
    ]
