# Generated by Django 4.2.16 on 2024-10-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_release_year"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameGenresPlatforms",
            new_name="GameСhoises",
        ),
    ]
