# Generated by Django 4.2.16 on 2024-11-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="img/default_avatar.jpg",
                null=True,
                upload_to="users_avatars/",
            ),
        ),
    ]
